- title: Proposer
  description: Création de profil de compétences vivantes en 5 minutes
  image: assets/icons/pointing-up.png
- title: Trouver
  description: Recherche intuitive et contact directe en 10 secondes.
  image: assets/icons/handshake.png
- title: Remercier
  description: Reconnaissance entre pairs des compétences partagées
  image: assets/icons/clap.png
- title: Inviter
  description: Propagation de pair-à-pair en 1 clic
  image: assets/icons/waving.png
- title: Présenter
  description: Mise en relation de 2 autres collaborateurs en 1 clic
  image: assets/icons/pointing-right.png
- title: Reconnaître
  description: Suggestion de compétences entre pairs
  image: assets/icons/thumbup.png
- title: Suggérer
  description: Assistance à la création de profil par Intelligence Artificielle
  image: assets/icons/robot.png
- title: Localiser
  description: Géolocalisation et carte de vos collaborateurs
  image: assets/icons/pin.png
- title: Protéger
  description: Sécurité et conformité RGPD exemplaire
  image: assets/icons/shield.png
